### ISSUE TITLE
Article Consistency on Competition Page

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#19]
There are a few issues of discrepancy between articles attached to the Competition page, and I was hoping you could check them out:

Under: "Why Submit?" , if we don't add the little "dash" at the top, "Prizes" is almost flush against "Why Submit?" 

But if you compare it to the section above, "Deadlines", there is nothing different between the sections (except, it looks like, we've used different # commands to get the text to appear the same way). 

Can you look into why that's happening?

**Comment by brendanmetzger** [comment]
It looks like it's happening due to a little different with the tags used. ### is a level 3 heading, and #### is level 4. Stylistically, they are identical except the ### has a margin on top. (I didn't remember this off hand, but see now that I checked).

Anyway, I changed the copy to ### and it looks like everything looks appropriate.
