### ISSUE TITLE
Dev Site --> Real Site!

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#39]
Not sure what the best way to tell you this is, but could you make all of the changes that you've added to our Dev Site live on www.thirdcoastfestival.org?

**Comment by brendanmetzger** [comment]
Ok—pulled them in. Might have to refresh a few times to clear the cache. @TCEmkenn —I'm, noticing that all the sponsor footer is now on top of the footer, but all the sponsor logos went away? Maybe that was on your end, but just double checking in case something went awry.

**Comment by TCEmkenn** [comment]
I'm seeing that all of the foundation logos went away, too! I wanted to ask you about that!

I don't know what happened? That wasn't intentional on my part, lol—I want them back! Do you have an idea of what may have happened?

**Comment by brendanmetzger** [comment]
Ok, I added them back in—they had been deleted at some point—It looks like quite a bit of stuff had been removed, but added the sponsors back in. Let me know if the other stuff needs to be put back in otherwise I'll assume things are in good shape now.

FYI, the data store and the site are separate operations, so modifications to one rarely affect the other, for some peace of mind.

**Comment by TCEmkenn** [comment]
OH! It was me. It WAS ME. That is my extreme bad. 

Sigh. OK. I see what I did, which was respond to a request to remove the list on the About Page. So, I'll kick it to you:

- Can you hide/remove the list version of the "2020 FOUNDATION SUPPORT" on the About Page, but keep the logo design above the footer exactly as it is? 
- Once you do that: Will I still be able to attach new foundation logos to the list footer by logging in from the About page?

**Comment by brendanmetzger** [comment]
Yep, I'll remove the list from the about page.  You can still edit the about page and have the footer logos change though. To clarify, the about page is a template that pulls in the TCF org for its data... you can think of them as somewhat synonymous if that helps keep things straight, but the TCF org has business all over the place (including tracking the footer sponsors) where the about page is just organizing and displaying certain pieces of information.

**Comment by brendanmetzger** [comment]
In fact, I should probably amend that and give an understanding of what templates do, they are just organize data into some visual outcome.. at their best they are extremely simple and expendable components. This gets back into our convo the other day about user control vs. data integrity and being able to redesign things. The smarter templates get, the harder it is to redo or migrate anything going forward, because they know too much.

So I'll say as a rule of thumb, if you want something removed from a template and the data is no longer relevant, delete the data. If you want to remove something and the data is still relevant, adjust the template. Kinda dense I suppose, but once you wrap your head around it it makes sense.

analogy.. maybe?

Template = recipe
Database = pantry/fridge
Datum = ingredient

a meal is composed from a recipe using several ingredients from the pantry
a webpage is composed from a template using several datums from the database
