### ISSUE TITLE
Competition Page: Link Issues

### ISSUE THREAD

**Issue by TCEmkenn** [Third-Coast/website#46]

**Comment by TCEmkenn** [comment]
Link issues:

- [ ] Seemingly everywhere on the website, if we create a link to something and then add a period after it, it will save once looking fine, but if we re-edit that page/article/etc, it will add an extra space between the word & and the period. A good example is [on the Competition page right now](https://www.thirdcoastfestival.org/competition/2021-tcrhdf-competition) in the sentence: "A note from Third Coast: Please be sure to read through our introduction below before entering. For updates on the 2021 Competition, plus more from Third Coast, make sure you’re signed up for our weekly-ish Producer News ."

- [ ] Weirdly, some of the links we have currently are not working on Safari. We think it might be an asterisk problem when we are bolding links on the backend — that Safari isn't reading our asterisk placement, but other browsers are. We're testing this problem right now, but I thought you might have an idea.

**Comment by brendanmetzger** [comment]
I see what you mean about the first one—looks like a bug in the markdown processor isn't compiling quite right. I used a 3rd party script back when I made the site, so I'm not totally familiar with the mechanics, but I'll see if I can spot anything.

Re. the links in 2nd bullet, do you have a page with an example? I'm thinking it is related to the first issue in that markdown is mangling something.

**Comment by brendanmetzger** [comment]
Oh, NM I see its the same damn link in safari!

**Comment by brendanmetzger** [comment]
@TCEmkenn,

First issue was indeed a bug in the markdown thing—that's resolved. The non-functional links appear to be a bizarre safari quirk. Current have bold tag IN a link tag, which it totally fine, but safari isn't having it in this instance. It will, however, allow you to put a link tag IN a bold tag... so that, unfortunately, will be the solution for now.

Old:
`[**Producer News**](https://signup.e2ma.net/signup/1411915/1400216/).*`

Can be:
`**[Producer News](https://signup.e2ma.net/signup/1411915/1400216/)**.*`

**Comment by TCEmkenn** [comment]
OK perfect. Thanks for this.

*Emily S. Kennedy* | Program Director | Third Coast Festival
<http://thirdcoastfestival.org/>

ekennedy@thirdcoastfestival.org | Pronouns: She/Her/Hers
